#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python_bin="${PYTHON:-python3.10}"
python_version="$("${python_bin}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

if [[ "${python_version}" != "3.10" ]]; then
  echo "Constraint refresh must use Python 3.10; got ${python_version}." >&2
  echo "Set PYTHON to a Python 3.10 interpreter and retry." >&2
  exit 2
fi

temporary_dir="$(mktemp -d)"
trap 'rm -rf "${temporary_dir}"' EXIT
venv_dir="${temporary_dir}/venv"
candidate="${temporary_dir}/dev.txt"

"${python_bin}" -m venv "${venv_dir}"
venv_python="${venv_dir}/bin/python"
"${venv_python}" -m pip install \
  --disable-pip-version-check \
  --no-cache-dir \
  -e "${repo_root}[pdf,dev]"

{
  echo "# Generated by PYTHON=python3.10 ./scripts/refresh-constraints.sh"
  echo "# Review every diff; do not hand-edit this file."
  echo "# Validate on Python 3.10 and 3.13 before accepting a refresh."
  echo "# pip is the environment bootstrap tool and is intentionally not constrained."
  "${venv_python}" -m pip list \
    --disable-pip-version-check \
    --format=freeze \
    --exclude=honeymoney \
    --exclude=pip | LC_ALL=C sort -f
} >"${candidate}"

mkdir -p "${repo_root}/constraints"
mv "${candidate}" "${repo_root}/constraints/dev.txt"
echo "Updated constraints/dev.txt using Python ${python_version}."
