from typing import Final, Mapping, Sequence

from honeymoney.identity_contracts import IdentityManifest, IdentityRow

IDENTITY_MANIFEST_NAME: Final[str]
ID_FIELDS: Final[tuple[str, ...]]

class IdentityError(ValueError): ...

def record_fingerprint(row: IdentityRow) -> str: ...
def normalized_decimal(value: object) -> str: ...
def normalized_record_identity(row: IdentityRow) -> dict[str, str]: ...
def has_stable_v2_identity(row: IdentityRow) -> bool: ...
def ambiguous_legacy_transaction_ids(rows: Sequence[IdentityRow]) -> frozenset[str]: ...
def empty_manifest() -> IdentityManifest: ...
def manifest_document(manifest: Mapping[str, object]) -> str: ...
def parse_manifest(document: str | bytes) -> IdentityManifest: ...
def validate_ledger_manifest_agreement(
    ledger_rows: Sequence[Mapping[str, str]],
    manifest: IdentityManifest,
) -> None: ...
